name: Test

on:
  push:
    branches: ["master"]
    paths:
      - "**/*.rs"
  pull_request:
    branches: ["master"]
    paths:
      - "**/*.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - name: default
            cargo_args: ""
          - name: jit
            cargo_args: "--features jit"
    runs-on: ubuntu-latest
    name: test (${{ matrix.profile.name }})

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose --all-targets ${{ matrix.profile.cargo_args }}
